/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 28!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        int[] arr = { 10, 7, 8, 9, 1, 5 };
        int n = arr.length;

        quickSortMain(arr, 0, n - 1);

//        QuickSort qs = new QuickSort();
//        qs.quickSort(arr, 0, n - 1);
//        System.out.println("Sorted array: ");
//        qs.printArray(arr, n);
    }
    public static ArrayList quickSortMain(int arr[], int x ,int y){
        QuickSort qs = new QuickSort();
        qs.quickSort(arr, x, y);
        qs.printArray(arr, y+1);
        return qs.testArray(arr);
    }
}
