/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 13";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try {
            System.out.println(validateBrackets("[}"));
        } catch (Exception e) {
            e.printStackTrace();
          //  System.out.println(false);
        }
    }

    public static boolean validateBrackets(String s) {

        Stack<Character> stack = new Stack<>();

        for(int i=0 ; i<s.length() ;i++ ){
            if (s.charAt(i) == '{' || s.charAt(i) == '(' || s.charAt(i) == '[') {
                stack.push(s.charAt(i));
            }
            try {
                if (s.charAt(i) == '}' && stack.peak() == '{') {
                    stack.pop();
                }else if (s.charAt(i) == ')' && stack.peak() == '(') {
                    stack.pop();
                }else if (s.charAt(i) == ']' && stack.peak() == '[') {
                    stack.pop();
                }
            } catch (Exception e) {
                return false;
            }
        }
        System.out.println(stack.stackArr);

        return !stack.isEmpty();
    }
}
