/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void checkDFT() throws Exception {

        Graph g = new Graph();
        g.addEdge(1, 2, true);
        g.addEdge(2, 3, true);
        g.addEdge(2, 4, true);
        g.addEdge(3, 4, true);
        g.addEdge(3, 5, true);
        g.addEdge(5, 6, true);
        assertEquals("[1, 2, 3, 4, 5, 6]",String.valueOf(App.bftGraph(g,1)));
    }
}
