/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 30!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        Map<String, Integer> map = new Map<>();
//        map.add("this", 1);
//        map.add("coder", 2);
//        map.add("this", 4);
//        map.add("hi", 5);
//        System.out.println(map.size());
//        System.out.println(map.remove("this"));
//        System.out.println(map.remove("this"));
//        System.out.println(map.size());
//        System.out.println(map.isEmpty());
    }
}
