/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testInsertandCollection(){
        assertEquals("[10, 20, 30]", String.valueOf(App.toTestInsert(10,20,30)));
    }
    @Test public void testCreationOfLinkedList(){
        assertEquals("[]", String.valueOf(App.toTestEmpty()));
    }
    @Test public void testHead(){
        assertEquals("10", String.valueOf(App.checkHead(10,20,30)));
        assertEquals(10, App.checkHead(10,20,30));
    }
    @Test public void testInsertOne(){
        assertEquals("[3]", String.valueOf(App.toTestInsertOne(3)));
    }
    @Test public void testIncludes(){
        assertEquals(false, (App.toTestIncludes(10,20,30,80)));
        assertEquals(true, (App.toTestIncludes(10,20,30,20)));
    }

//
//
//    @Test
//    public void test() {
//        LinkedList list = new LinkedList();
//        Assert.assertEquals("Value Added", list.insert(5));
//
//    }
//    @Test
//    public void includeTest(){
//        LinkedList list = new LinkedList();
//        list.insert(5);
//        list.insert(7);
//        assertEquals(true, list.includes(7) );
//        assertEquals(false, list.includes(8) );
//    }
//
//    @Test void  getStringTest(){
//        LinkedList list = new LinkedList();
//        list.insert(5);
//        list.insert(7);
//        assertEquals("{ 5 } -> { 7 } -> NULL", list.getAsString());
//
//    }


}
