/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testMethods(){
//        LinkedList list = new LinkedList();
//        list.append(45);
//        list.append(75);
//        list.append(69);
//        list.append(21);
//        list.append(36);
        assertEquals( "[8]" , String.valueOf(App.appending(8)));
        assertEquals( "[8, 55, 12]" , String.valueOf(App.appendingMult(8,55,12)));
        assertEquals( "[45, 75, 69, 8, 21, 36]" , String.valueOf(App.addAfter(69,8)));
        assertEquals( "[45, 75, 69, 21, 36, 8]" , String.valueOf(App.addAfter(36,8)));
        assertEquals( "[45, 75, 8, 69, 21, 36]" , String.valueOf(App.addBefore(69,8)));
        assertEquals( "[8, 45, 75, 69, 21, 36]" , String.valueOf(App.addBefore(45,8)));
    }
}
