/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testBracketsMethod(){

        assertTrue(App.validateBrackets("(){hello}({})"));
        assertTrue(App.validateBrackets("([{}])"));
        assertFalse(App.validateBrackets("}{"));
        assertFalse(App.validateBrackets("{(})"));
        assertFalse(App.validateBrackets("{]"));
    }
}
