/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;

import java.util.Queue;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void pseudoCodeMthods() throws Exception {
        PseudoQueue q = new PseudoQueue<>();
        // Testing adding to empty queue
        assertEquals("10", App.enQ(q,10));
        q.enqueue(20);
        q.enqueue(30);
        // Testing adding to non-empty queue
        assertEquals("40->30->20->10", App.enQ(q,40));
        // Testing removing from non-empty queue
        assertEquals("10", App.deQ(q));
        App.deQ(q);
        App.deQ(q);
        App.deQ(q);
        // Testing removing from empty queue
        boolean thrown = false;
        try{
            App.deQ(q);
        }catch (Exception e){
            thrown=true;
        }
        assertTrue(thrown);
    }
}
