/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 36!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph g = new Graph();
        g.addEdge(1, 2, true);
        g.addEdge(2, 3, true);
        g.addEdge(2, 4, true);
        g.addEdge(3, 4, true);
        g.addEdge(3, 5, true);
        g.addEdge(5, 3, true);
        g.addEdge(5, 6, true);

       // System.out.println(g.getNodes());

        Node head = new Node(3);
        try {
            System.out.println(g.breadthFirstTraversal(head));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
