/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 31!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        splittingBookStringToWords("This is a sample sentence.");


    }

    public static void splittingBookStringToWords(String book){
        String[] words = book.split("\\s+");
        for (int i = 0; i < words.length; i++) {
            // You may want to check for a non-word character before blindly
            // performing a replacement
            // It may also be necessary to adjust the character class
            words[i] = words[i].replaceAll("[^\\w]", "");
            System.out.println(words[i]);
        }
    }
}
