/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testGettingTheFirstRepeatedWord(){
        assertEquals("hello",App.gettingTheFirstRepeatedWord(App.splittingBookStringToWords(
                "Hello, hello, hi, hello hi how are you hi")));

        assertEquals("hello",App.gettingTheFirstRepeatedWord(App.splittingBookStringToWords(
                "Hello hello hi hello hi how are you hi")));

        assertEquals("hello",App.gettingTheFirstRepeatedWord(App.splittingBookStringToWords(
                "hello hi hello hi how are you hi")));
    }
}
