/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

import org.junit.jupiter.api.Test;

import javax.swing.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void fizzBuzz(){

        KaryTree tree = new KaryTree();
        Node parent= new Node(0);
        parent.child.add(new Node(75));
        parent.child.add(new Node(13));
        parent.child.add(new Node(9));

        Node r0 = (Node) parent.child.get(0);
        r0.child.add(new Node(25));
        r0.child.add(new Node(8));
        Node r1 = (Node) parent.child.get(1);
        r1.child.add(new Node(30));
        r1.child.add(new Node(18));
        Node r2 = (Node) parent.child.get(2);
        r2.child.add(new Node(34));
        r2.child.add(new Node(80));

        assertEquals("[FizzBuzz, FizzBuzz, num: 13, Fizz, Buzz, num: 8, FizzBuzz, Fizz, num: 34, Buzz]", String.valueOf(App.fizzBuzzarr(tree,parent)));
    }
}
