/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc;

public class App {
    public String getGreeting() {
        return "Hello From Code Challenge 35!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        // Object of graph is created.
        Graph<Integer> g = new Graph<Integer>();

        // edges are added.
        // Since the graph is bidirectional,
        // so boolean bidirectional is passed as true.
        g.addEdge(0, 1, true);
        g.addEdge(0, 4, true);
        g.addEdge(1, 2, true);
        g.addEdge(1, 3, true);
        g.addEdge(1, 4, true);
        g.addEdge(2, 3, true);
        g.addEdge(3, 4, true);

        // print the graph.
        System.out.println("Graph:\n"
                + g.getNodes());

        // gives the no of vertices in the graph.
        g.getVertexCount();


        System.out.println(g.getNeighbour(1));




    }
}
